# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "matrikkel-keycloak"
  tags:
  - "public"
spec:
  type: "service"
  lifecycle: "production"
  owner: "Heimdall"
  system: "matrikkel"
  providesApis:
  - "matrikkel-keycloak-api"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "security_champion_matrikkel-keycloak"
  title: "Security Champion matrikkel-keycloak"
spec:
  type: "security_champion"
  parent: "eiendom_security_champions"
  members:
  - "lislei"
  children:
  - "resource:matrikkel-keycloak"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "matrikkel-keycloak"
  links:
  - url: "https://github.com/kartverket/matrikkel-keycloak"
    title: "matrikkel-keycloak på GitHub"
spec:
  type: "repo"
  owner: "security_champion_matrikkel-keycloak"
  dependencyOf:
  - "component:matrikkel-keycloak"
---
apiVersion: "backstage.io/v1alpha1"
kind: "API"
metadata:
  name: "matrikkel-keycloak-api"
  tags:
  - "public"
spec:
  type: "openapi"
  lifecycle: "production"
  owner: "Heimdall"
  definition: |
    openapi: "3.0.0"
    info:
        title: matrikkel-keycloak API
    paths:
