services:
  keycloak:
    image: ghcr.io/kartverket/matrikkel-keycloak:latest
    build:
      dockerfile: Dockerfile
      args:
        KC_DB: "dev-mem"
    user: "150"
    ports:
        - "8080:8080"
    env_file:
      - ./local.env
