#!groovy

@Library('common') _

pipeline {
    agent {
        label 'matrikkelen'
    }

    tools {
        jdk 'Java 17 Latest'
    }

    environment {
        MAVEN_PUBLISH = credentials('MAVEN_DEPLOY_RELEASE_CANDIDATE')
    }

    stages {
        stage('Prepare') {
            steps {
                sh "./gradlew clean assemble --refresh-dependencies -Dsuffix=-rc-${BUILD_NUMBER}"
            }
        }
        stage('Publish release-candidate') {
            when {
                branch 'main'
            }
            steps {
                sh "./gradlew publish -Dsuffix=-rc-${BUILD_NUMBER}"
            }
        }
    }

    options {
        buildDiscarder(logRotator(artifactNumToKeepStr: '30', numToKeepStr: '90'))
        skipStagesAfterUnstable()
        timeout(time: 60, unit: 'MINUTES')
        timestamps()
    }

    post {
        unsuccessful {
            pushBuildFeed()
        }
    }
}

