#!groovy

@Library('common@master') _

pipeline {
    agent {
        label 'matrikkelen'
    }

    tools {
        jdk 'Java 11 Latest'
    }

    environment {
        MAVEN_PUBLISH = credentials('MAVEN_DEPLOY_RELEASE_CANDIDATE')
        GRADLE_USER_HOME = "$WORKSPACE/.gradle" // Forhindre samtidighetsproblemer
        GRADLE_OPTS =
            '-Dorg.gradle.daemon=false ' +
            "-Dmaven.repo.local=$WORKSPACE/.m2/repository" // Forhindre samtidighetsproblemer
    }

    stages {
        stage('Prepare') {
            steps {
                sh "./gradlew clean assemble --refresh-dependencies -Dsuffix=-rc-${script.env.BUILD_NUMBER}"
            }
        }
        stage('Publish release-candidate') {
            when { branch 'master' }
            steps {
                sh "./gradlew publish -Dsuffix=-rc-${script.env.BUILD_NUMBER}"
            }
        }
    }

    options {
        buildDiscarder(logRotator(artifactNumToKeepStr: '30', numToKeepStr: '90'))
        skipStagesAfterUnstable()
        timeout(time: 60, unit: 'MINUTES')
        timestamps()
    }

    post {
        unsuccessful {
            pushBuildFeed()
        }
    }
}
